client localhost {
    ipaddr = 127.0.0.1
    proto = *
    secret = __RADIUS_SECRET__
    limit {
        max_connections = 16
        lifetime = 0
        idle_timeout = 900
    }
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = __RADIUS_SECRET__
}


client docker-host {
    ipaddr = 172.25.0.1
    secret = __RADIUS_SECRET__
    shortname = docker-host
    require_message_authenticator = no
}

client docker-net {
    ipaddr = 172.25.0.0/24
    secret = __RADIUS_SECRET__
    shortname = docker-net
    require_message_authenticator = no
}



client wireguard-subnet {
    ipaddr = 10.0.0.0/24
    secret = __RADIUS_SECRET__
    shortname = wireguard-clients
    nas_type = other
}
